// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuExY6DrkcWk8RrHMWtK9g1YjQGWGN8Ow',
    appId: '1:452659130765:web:647e37956426deedf98dc4',
    messagingSenderId: '452659130765',
    projectId: 'detabase-518a3',
    authDomain: 'detabase-518a3.firebaseapp.com',
    storageBucket: 'detabase-518a3.appspot.com',
    measurementId: 'G-8LRWZDDFF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbR_0EC2V78mnxAluCDLS1LvVl5VzD9UA',
    appId: '1:452659130765:android:42ac78b6d9e8bbe8f98dc4',
    messagingSenderId: '452659130765',
    projectId: 'detabase-518a3',
    storageBucket: 'detabase-518a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb74oJrG8mtYU1NeojgNxdm5-_Wcl4k4Y',
    appId: '1:452659130765:ios:71c78c99ab43a2c9f98dc4',
    messagingSenderId: '452659130765',
    projectId: 'detabase-518a3',
    storageBucket: 'detabase-518a3.appspot.com',
    iosBundleId: 'com.example.banglaBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb74oJrG8mtYU1NeojgNxdm5-_Wcl4k4Y',
    appId: '1:452659130765:ios:71c78c99ab43a2c9f98dc4',
    messagingSenderId: '452659130765',
    projectId: 'detabase-518a3',
    storageBucket: 'detabase-518a3.appspot.com',
    iosBundleId: 'com.example.banglaBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuExY6DrkcWk8RrHMWtK9g1YjQGWGN8Ow',
    appId: '1:452659130765:web:572226473c462dc9f98dc4',
    messagingSenderId: '452659130765',
    projectId: 'detabase-518a3',
    authDomain: 'detabase-518a3.firebaseapp.com',
    storageBucket: 'detabase-518a3.appspot.com',
    measurementId: 'G-V27P297SMD',
  );

}